language: java
jdk:
 - oraclejdk8
script:
  - mvn install
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/actionreplay*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
after_success:
  - artefact="$(basename target/actionreplay*.jar .jar)"
  - tag="$(cut -d '-' -f 2- <<< $artefact)"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$tag-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG